source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import UserRegisterView, UserProfile, logout_view, subscribe_view, UserProfileEdit
from feed.views import PostCreateView, PostDetailedView

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/sign_in.html'), name='log_in'),
    path('create/', UserRegisterView.as_view(), name='register_user'),
    path('profile/<int:profile_pk>', UserProfile.as_view(), name='profile'),
    path('profile/<int:profile_pk>/edit', UserProfileEdit.as_view(), name='edit_profile'),
    path('profile/<int:profile_pk>/subscribe/', subscribe_view, name='profile_sub'),
    path('logout/', logout_view, name='log_out'),
    path('<int:profile_pk>/new_post/', PostCreateView.as_view(), name='new_post'),
    path('profile/<int:profile_pk>/post/<int:post_pk>/', PostDetailedView.as_view(), name='detailed_post')
]

source/api_v1/urls.py
from django.urls import include, path
from rest_framework import routers
from api_v1 import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api_v1'

router = routers.DefaultRouter()
router.register(r'posts', views.PostViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('like/<int:like_pk>/', views.LikeView.as_view(), name='api_like')
]

source/mygram/urls.py
from django.contrib import admin
from django.urls import path, include
from feed.views import FeedView, post_like_view, PostDetailedView, SearchResultsView
from accounts.views import UserRegisterView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', FeedView.as_view(), name='feed'),
    path('sign_up/', UserRegisterView.as_view()),
    path('feed/<int:post_pk>/', PostDetailedView.as_view(), name='feed_post'),
    path('search_result/', SearchResultsView.as_view(), name='search_results'),
    path('likes/', post_like_view, name='post_likes'),
    path('api/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Profile(AbstractUser):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    avatar  = models.ImageField('Аватар', upload_to='user_pics')
    name = models.CharField('Имя', max_length=100, blank=True, null=True)
    info = models.TextField('Инфо', max_length=1000, blank=True, null=True)
    number = models.IntegerField('Номер телефона', blank=True, null=True)
    subs = models.ManyToManyField('Profile', blank=True, null=True, related_name='my_subs')
    sex = models.CharField('Пол', max_length=1, blank=False, null=True, choices=GENDER_CHOICES, default='M')

    def __str__(self):
        return self.username
    

source/accounts/forms.py
from accounts.models import Profile
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class NewUserForm(UserCreationForm):
    class Meta:
        model = Profile
        fields = [
            'username', 'password1', 'password2',
            'first_name', 'avatar', 'email', 
            'info', 'number', 'sex'
        ]
        widgets = {
            'username' : forms.TextInput(attrs={'placeholder': 'Логин', 'class': 'input_box'}),
            'first_name' : forms.TextInput(attrs={'placeholder': 'Имя', 'class': 'input_box'}),
            'email' : forms.EmailInput(attrs={'placeholder': 'Электронная почта', 'class': 'input_box'}),
            'info' : forms.Textarea(attrs={'placeholder': 'О себе', 'class': 'input_box text_box'}),
            'number' : forms.NumberInput(attrs={'placeholder': 'Номер телефона', 'class': 'input_box'}),
            'sex' : forms.RadioSelect(attrs={'placeholder': 'Пол', 'class': 'input_box d-flex flex-row justify-content-around'}),
        }
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if len(email) < 1:
            raise forms.ValidationError("Email обязателен к заполнению!")
        return email
    
    def clean(self):
        cleaned_data = super().clean()
        if len(cleaned_data['first_name']) < 1:
            raise forms.ValidationError("Хотя бы одно поле ИМЕНИ должно быть заполнено")
        return cleaned_data
    
class UserEditForm(UserChangeForm):
    class Meta:
        model= Profile
        fields = [
            'first_name', 'avatar', 'email', 
            'info', 'number', 'sex'
        ]
        widgets = {
            'first_name' : forms.TextInput(attrs={'placeholder': 'Имя', 'class': 'input_box'}),
            'email' : forms.EmailInput(attrs={'placeholder': 'Электронная почта', 'class': 'input_box'}),
            'info' : forms.Textarea(attrs={'placeholder': 'О себе', 'class': 'input_box text_box'}),
            'number' : forms.NumberInput(attrs={'placeholder': 'Номер телефона', 'class': 'input_box'}),
            'sex' : forms.RadioSelect(attrs={'placeholder': 'Пол', 'class': 'input_box d-flex flex-row justify-content-around'}),
        }

        

source/accounts/views.py
from django.contrib.auth import login, logout
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from accounts.models import Profile
from accounts.forms import NewUserForm, UserEditForm
from typing import Any
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin

def logout_view(request):
    logout(request)
    return redirect('feed')

class UserRegisterView(CreateView):
    model = Profile
    template_name = 'accounts/sign_up.html'
    form_class = NewUserForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(reverse('feed'))
    
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('feed')
        return next_url
    
class UserProfile(LoginRequiredMixin, DetailView):
    login_url = 'accounts:log_in'
    template_name = 'accounts/profile_page.html'
    model = Profile
    context_object_name = 'profile_obj'
    pk_url_kwarg = 'profile_pk'

def subscribe_view(request, profile_pk):
    profile_obj = Profile.objects.get(id=request.POST.get('profile_id'))
    if request.user.subs.filter(id=profile_obj.id).exists():
        request.user.subs.remove(profile_obj)
    else:
        request.user.subs.add(profile_obj)
    print(request.POST)
    return HttpResponseRedirect(reverse('accounts:profile', args=[str(profile_pk)]))


class UserProfileEdit(LoginRequiredMixin, UpdateView):
    login_url = 'accounts:log_in'
    model = Profile
    form_class = UserEditForm
    template_name = 'accounts/edit_profile.html'
    pk_url_kwarg = 'profile_pk'
    context_object_name = 'profile_obj'

    def get_success_url(self, **kwargs):
        return reverse('accounts:profile', kwargs={'profile_pk': self.request.user.pk})
    
    def get_context_data(self, **kwargs):
        kwargs['profile_obj'] = self.get_object()
        kwargs['form'] = self.get_form()
        return super().get_context_data(**kwargs)
    

source/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}    
    <div class="card card_form mt-5">
        <img src="{{profile_obj.avatar.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Редактирование профиля</h5>  
            <div class="form-control mb-3 mt-3">{{form.email}}</div>
            <div class="form-control mb-3 mt-3">{{form.avatar}}</div>
            <div class="form-control mb-3 mt-3">{{form.first_name}}</div>
            <div class="form-control mb-3 mt-3">{{form.info}}</div>
            <div class="form-control mb-3 mt-3">{{form.number}}</div>
            <div class="form-control mb-3 mt-3">{{form.sex}}</div>
            <button type="submit" class="btn btn-primary">Подтвердить</button>
        </div>
      </div>
</form>
{% endblock %}

source/templates/accounts/profile_page.html
{% extends "base.html" %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block title %}Main Page{% endblock %}
{% block content %}
        <div class="container mt-5">
            <div class="usr_info d-flex flex-row justify-content-around" style="width: 50%;">
                <div class="usr_avatar" style="width: 20%;">
                    <img class="user_avatar" src="{{profile_obj.avatar.url}}" style="width: 100%;" alt="">
                </div>
                <div class="text_info">
                    <div class="usr_name">
                        <div class="d-flex flex-row">
                            <h3>{{profile_obj.username}}</h3>
                            <a href="{% url 'accounts:edit_profile' profile_obj.pk %}" class="btn btn-secondary ms-5">Редактирование</a>
                        </div>
                        {% if request.user != profile_obj %}
                        <form method='post' action="{% url 'accounts:profile_sub' profile_obj.pk %}">
                            {% csrf_token %}
                            <button class="btn" type="submit" name="profile_id", value="{{profile_obj.pk}}">
                              {% if profile_obj in request.user.subs.all %}
                                <i class="bi bi-bookmark-heart-fill text-warning fs-2"></i>
                              {% else %}
                                <i class="bi bi-bookmark-heart fs-2"></i>
                              {% endif %}
                            </button>
                          </form>
                        {% endif %}
                    </div>
                    <div class="counts mt-3">
                        <span>{{profile_obj.usr_posts.all.count}} Публикаций</span>
                        <span>{{profile_obj.subs.all.count}} Подписки</span>
                        <span>{{profile_obj.my_subs.all.count}} Подписчики</span>
                    </div>
                    <div class="usr_bio mt-3">
                        <h6>{{profile_obj.first_name}}</h6>
                        <p>{{profile_obj.info}}</p>
                    </div>
                </div>
            </div>
            <div class="posts d-flex flex-row mt-3">
                {% for post in profile_obj.usr_posts.all %}
                <div class="card m-3 justify-content-center" style="width: 18rem;">
                    <a href="{% url 'accounts:detailed_post' user.pk post.pk %}"><img src="{{post.image.url}}" class="card-img-top" style="width: 100%; object-fit: contain;"></a>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}

source/templates/accounts/sign_in.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<form method="post">
{% csrf_token %}    
    <div class="card card_form mt-5">
        <img src="{% static 'images/title2.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Вход</h5> 
            <div class="form-control mt-3">{{form.username}} <span>Логин</span></div>
            <div class="form-control mt-3">{{form.password}} <span>Паролль</span></div>
            <button type="submit" class="btn btn-primary mt-3">Войти</button>
            <a href="{% url 'accounts:register_user' %}" type="submit" class="btn btn-primary mt-3">Регистрация</a> 
        </div>
      </div>
</form>
{% endblock %}

source/templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<form method="post">
{% csrf_token %}    
    <div class="card card_form">
        <img src="{% static 'images/title2.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Регистрация</h5>  
            <div class="form-control mb-3 mt-3">{{form.username}}</div>
            <div class="form-control mb-3 mt-3">{{form.email}}</div>
            <div class="form-control mb-3 mt-3">{{form.avatar}}</div>
            <div class="form-control mb-3 mt-3">{{form.password1}}</div>
            <div class="form-control mb-3 mt-3">{{form.password2}}</div>
            <div class="form-control mb-3 mt-3">{{form.first_name}}</div>
            <div class="form-control mb-3 mt-3">{{form.info}}</div>
            <div class="form-control mb-3 mt-3">{{form.number}}</div>
            <div class="form-control mb-3 mt-3">{{form.sex}}</div>
            <button type="submit" class="btn btn-primary">Подтвердить</button>
        </div>
      </div>
</form>
{% endblock %}