source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import UserRegisterView, UserProfile, logout_view, subscribe_view, UserProfileEdit
from feed.views import PostCreateView, PostDetailedView

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/sign_in.html'), name='log_in'),
    path('create/', UserRegisterView.as_view(), name='register_user'),
    path('profile/<int:profile_pk>', UserProfile.as_view(), name='profile'),
    path('profile/<int:profile_pk>/edit', UserProfileEdit.as_view(), name='edit_profile'),
    path('profile/<int:profile_pk>/subscribe/', subscribe_view, name='profile_sub'),
    path('logout/', logout_view, name='log_out'),
    path('<int:profile_pk>/new_post/', PostCreateView.as_view(), name='new_post'),
    path('profile/<int:profile_pk>/post/<int:post_pk>/', PostDetailedView.as_view(), name='detailed_post')
]

source/api_v1/urls.py
from django.urls import include, path
from rest_framework import routers
from api_v1 import views
from rest_framework.authtoken.views import obtain_auth_token

app_name = 'api_v1'

router = routers.DefaultRouter()
router.register(r'posts', views.PostViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('login/', obtain_auth_token, name='api_token_auth'),
    path('like/<int:like_pk>/', views.LikeView.as_view(), name='api_like')
]

source/mygram/urls.py
from django.contrib import admin
from django.urls import path, include
from feed.views import FeedView, post_like_view, PostDetailedView, SearchResultsView
from accounts.views import UserRegisterView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', FeedView.as_view(), name='feed'),
    path('sign_up/', UserRegisterView.as_view()),
    path('feed/<int:post_pk>/', PostDetailedView.as_view(), name='feed_post'),
    path('search_result/', SearchResultsView.as_view(), name='search_results'),
    path('likes/', post_like_view, name='post_likes'),
    path('api/', include('api_v1.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/feed/models.py
from django.db import models
from accounts.models import Profile

class PostModel(models.Model):
    image = models.ImageField('Картинка', upload_to='post_images')
    user = models.ForeignKey(Profile, verbose_name='Пользователь', related_name='usr_posts', on_delete=models.CASCADE)
    text = models.TextField('Текст публикации', max_length=1000)
    likes = models.ManyToManyField(Profile, related_name='user_likes', blank=True)
    date_add = models.DateField('Дата публикации', auto_now_add=True)
    

class CommentModel(models.Model):
    author = models.ForeignKey(Profile, verbose_name='Автор', related_name='a_comment', on_delete=models.SET_NULL, blank=True, null=True)
    post_model = models.ForeignKey(PostModel, verbose_name='Продукт', related_name='p_comment', on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField('Текст отзыва', max_length=1500)
    date_add = models.DateField('Дата публикации', auto_now_add=True)
    date_edit = models.DateField('Дата редактирования', auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_author(self):
        return Profile.objects.get(username=self.author)
    
    def get_product(self):
        return Profile.objects.get(id=self.post_model)

source/feed/forms.py
from django.forms import ModelForm, Textarea
from feed.models import PostModel, CommentModel
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = PostModel
        fields = [
            'image',
            'text',

        ]
        widgets = {
            'text' : forms.Textarea(attrs={'placeholder': 'Описание', 'class': 'input_box text_box'}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = CommentModel
        fields = [
            'text'
        ]
        widgets = {
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Оставьте комментарий',
                'style': "height: 150px"
            })
        }

source/feed/views.py
from typing import Any
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from feed.forms import CommentForm, PostForm
from feed.models import PostModel
from accounts.models import Profile
from django.views.generic.edit import FormMixin
from django.db.models import Q
from django.http import JsonResponse
# Create your views here.

class SearchResultsView(LoginRequiredMixin, ListView):
    login_url = 'accounts:log_in'
    model = Profile
    template_name = "search_results.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        context['this_objects'] = self.get_queryset()
        print(context['this_objects'])
        return context
    
    def get_queryset(self):
        query = self.request.GET.get("q")
        this_objects = Profile.objects.filter(
            Q(username__icontains=query) | 
            Q(first_name__icontains=query) | 
            Q(email__icontains=query)
        )
        return this_objects
    
class FeedView(LoginRequiredMixin, ListView):
    login_url = 'accounts:log_in'
    template_name = 'feed.html'
    context_object_name = 'post_obj'
    model = PostModel


    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        context['post_obj'] = PostModel.objects.all().order_by('date_add')
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:log_in'
    template_name = 'content/new_post.html'
    form_class = PostForm
    model = PostModel

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        print(kwargs)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_invalid(self, form):
        print(form.data)
        print(form.errors)
        print(self.request.POST.dict())
        return redirect('feed')
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return redirect('feed')
 

def post_like_view(request):  
    post = PostModel.objects.get(id=request.POST.get('postid'))
    icon = ''
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        icon = '<i class="bi bi-heart text-danger fs-2"></i>'
    else:
        post.likes.add(request.user)
        icon = '<i class="bi bi-heart-fill text-danger fs-2"></i>'
    return JsonResponse({'count': post.likes.count(), 'icon': icon})


class PostDetailedView(LoginRequiredMixin, FormMixin, DetailView):
    login_url = 'accounts:log_in'
    template_name = 'detailed_post.html'
    model = PostModel
    form_class = CommentForm
    context_object_name = 'post'
    pk_url_kwarg = 'post_pk'

    def get_success_url(self, **kwargs) -> str:
        return reverse_lazy('feed')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.post_model = self.get_object()
        self.object.save()
        return super().form_valid(form)




    

source/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% block style %}{% endblock %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body style="background-color:rgb(230, 229, 227) !important;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="collapse navbar-collapse row justify-content-between">
            <div class="col-3 d-flex flex-row">
                <div class="col-2 text-center">
                    <a href="{% url 'feed' %}" class="link-dark">
                        <i class="bi bi-instagram dark fs-2"></i>
                    </a>
                </div>
                <div class="col-6"><img class="img-fluid" src="{% static 'images/title2.png' %}" alt="" width="180px"></div>
            </div>
            {% if user.is_authenticated %}
            <div class="col-4">
                <form action="{% url 'search_results' %}" method="get">
                    <input name="q" class="input_box" type="text" placeholder="Поиск" style="width: 70%; border: 2px solid rgb(230, 229, 227);border-radius:5px">
                </form>
            </div>
                <div class="col-2 text-center">
                    <a href="{% url 'accounts:log_out' %}" class="btn btn-danger">Выход</a>
                    <a href="{% url 'accounts:new_post' user.pk %}" class="btn btn-success">Публикация</a>
                    <a href="{% url 'accounts:profile' user.pk %}" class="link-dark">
                        <i class="bi bi-person dark fs-1"></i>
                    </a>
                </div>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        <div class="background"></div>
        {% block content %}{% endblock %}
    </div>
    {% if user.is_authenticated %}
        <script type="text/javascript">
            $(document).on('click', '#like', function(e){
                const artId = $(this).val()
                const btn = this
                e.preventDefault();
                $.ajax({
                    headers: {"X-CSRFToken": '{{csrf_token}}'},
                    type: 'POST',
                    url: `{% url 'post_likes' %}`,
                    data: {
                        postid: $(this).val(),
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        action: 'post'
                    },
                    success: function(json) {
                        let c = `"${artId}"`
                        btn.innerHTML = json['icon']
                        let counter = document.querySelector(`[data-artId=${c}]`)
                        counter.innerHTML = json['count']
                    },
                    error: function(xhr, errmsg, err){
                    }
                })
            })
        </script>
    {% endif %}   
</body>
</html>

source/templates/detailed_post.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<div class="user_feed">
    {% include 'partial/posts_form.html' %}
    <h6 id="write_comment">Написать комментарий</h6>
      <form method="post">
          {% csrf_token %}
          <div class="row">
              <div class="col-10">
                  {{form.text}}
              </div>
          </div>
          <button type="submit" class="btn btn-primary mt-3 mb-3">Комментировать</button>
      </form>
      {% for comment in post.p_comment.all %}
        <div class="task_box">
            <span class="fs-4 fw-medium">
                <a href="{% url 'accounts:profile' comment.get_author.pk %}" class="text-dark" style="text-decoration: none;">{{comment.get_author}}</a>
            </span>
            <p>{{comment.text}}</p>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

source/templates/feed.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<div class="user_feed">
    {% for post in post_obj %}
        {% if post.user in request.user.subs.all %}
            {% include 'partial/posts_form.html' %}
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

source/templates/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<div class="user_feed">
    {% for profile_obj in this_objects %}
    {% if profile_obj != request.user %}
    <div class="container mt-5">
        <div class="usr_info d-flex flex-row justify-content-around" style="width: 50%;">
            <div class="usr_avatar" style="width: 20%;">
                <a href="{% url 'accounts:profile' profile_obj.pk %}">
                    <img class="user_avatar" src="{{profile_obj.avatar.url}}" style="width: 100%;" alt="">
                </a>
            </div>
            <div class="text_info">
                <div class="usr_name">
                    <a href="{% url 'accounts:profile' profile_obj.pk %}" class="text-dark" style="text-decoration: none;">
                        <h3>{{profile_obj.username}}</h3>
                    </a>
                    <form method='post' action="{% url 'accounts:profile_sub' profile_obj.pk %}">
                        {% csrf_token %}
                        <button class="btn" type="submit" name="profile_id", value="{{profile_obj.pk}}">
                          {% if profile_obj in request.user.subs.all %}
                            <i class="bi bi-bookmark-heart-fill text-warning fs-2"></i>
                          {% else %}
                            <i class="bi bi-bookmark-heart fs-2"></i>
                          {% endif %}
                        </button>
                      </form>
                </div>
                <div class="counts">
                    <span>{{profile_obj.usr_posts.all.count}} Публикаций</span>
                    <span>{{profile_obj.subs.all.count}} Подписки</span>
                    <span>{{profile_obj.my_subs.all.count}} Подписчики</span>
                </div>
                <div class="usr_bio">
                    <h6>{{profile_obj.first_name}}</h6>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}